apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-demo-blue
  labels: { app: bg-demo, version: blue }
spec:
  replicas: 4
  selector:
    matchLabels: { app: bg-demo, version: blue }
  template:
    metadata:
      labels: { app: bg-demo, version: blue }
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:0.2.3
          args: ["-text=BLUE (v1)", "-listen=:5678"]
          ports:
            - containerPort: 5678
